[week-03-greedy] 1781, 1946
HYU-PS-STUDY/Baekjoon pull request #15
Opened 2024-02-14 12:48 UTC by clean2001

issue #8 
- [1946 신입 사원](https://www.acmicpc.net/problem/1946)
- [1781 컵라면](https://www.acmicpc.net/problem/1781)

2024-02-18 12:34 UTC, wonkyDD commented
1946 풀이 잘봤습니다! 저도 한쪽 순위로 정렬시킨다음에 나머지 순위기준으로 탐색해서 풀었어요!

근데 1781 풀이가 1946이랑 똑같은 거 같아요..! 제가 착각했다면 죄송합니다 👀

2024-02-18 12:35 UTC, wonkyDD requested changes
1946 풀이 잘봤습니다! 저도 한쪽 순위로 정렬시킨다음에 나머지 순위기준으로 탐색해서 풀었어요!

근데 1781 풀이가 1946이랑 똑같은 거 같아요..! 제가 착각했다면 죄송합니다 👀

2024-02-18 12:40 UTC, wimmings approved these changes

2024-02-18 12:40 UTC, wimmings commented on week04-greedy/clean2001/B1946.java
> +                    ++ans;
저도 첫번째 항목으로 정렬하고 두번째 항목으로 비교해서 풀었네요! 이렇게 비교하고 작은 값으로 갱신해주는 것이 핵심이었던 것 같습니다 !

2024-02-18 12:40 UTC, wimmings commented on week04-greedy/clean2001/B1946.java
> +            System.out.println(ans);
LGTM👍🏻 :)

2024-02-18 13:39 UTC, wonkyDD approved these changes

2024-02-19 02:59 UTC, leGit-y commented on week04-greedy/clean2001/B1781.java
> +        System.out.println(ans);
저는 우선순위 큐에 컵라면만 저장해두었어요! 그렇게 되면 compare 함수 override 하는 부분도 생략이 가능할 거 같네요 :) 참고하시라고 아래에 코드 넣어둘게요!

2024-02-19 03:00 UTC, leGit-y commented on week04-greedy/clean2001/B1781.java
> +        System.out.println(ans);
```
        PriorityQueue<Long> pq = new PriorityQueue<>(); // 컵라면이 적은 일이 위로 가도록

        for(int i=0; i<N; ++i) {
            long d = list.get(i).deadline;
            long c = list.get(i).cup;
            pq.add(c);
            if(d < pq.size())  
                pq.remove();            
        }

        long ans = 0;
        while(!pq.isEmpty()) {
            ans += pq.poll();
        }

        System.out.println(ans);
```

2024-02-19 03:01 UTC, leGit-y approved these changes

2024-02-19 03:31 UTC, merged